package navidrome

import (
	"fmt"
	"path/filepath"
	"strconv"
	"strings"
)

// RenderTOML produces the managed navidrome.toml. Every value here is a
// product decision from PLAN.md; the ownership marker on line one is what
// makes the file replaceable by UDL later.
func RenderTOML(cfg Config, resolved Resolved, ffmpegPath string) string {
	var b strings.Builder
	writeLine := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}

	writeLine("# %s", OwnershipMarker)
	writeLine("# Generated by UDL. Manual edits are replaced on the next setup apply.")
	writeLine("")
	writeLine("MusicFolder = %s", tomlString(resolved.MusicDir))
	writeLine("DataFolder = %s", tomlString(resolved.DataDir))
	writeLine("CacheFolder = %s", tomlString(resolved.CacheDir))
	writeLine("Address = %s", tomlString(cfg.Server.Address))
	writeLine("Port = %d", cfg.Server.Port)
	writeLine("")
	writeLine("# Date Added must come from APFS creation time, so modification time is")
	writeLine("# never used as a stand-in and UDL never has to rewrite file timestamps.")
	writeLine("RecentlyAddedByModTime = false")
	writeLine("")
	writeLine("PlaylistsPath = %s", tomlString(resolved.PlaylistsPath))
	writeLine("AutoImportPlaylists = true")
	writeLine("EnableFavourites = true")
	writeLine("EnableStarRating = true")
	writeLine("EnableDownloads = true")
	writeLine("EnableSharing = false")
	writeLine("")
	writeLine("# Home LAN only in v1: no external lookups, no telemetry.")
	writeLine("EnableExternalServices = false")
	writeLine("EnableInsightsCollector = false")
	writeLine("")
	if ffmpegPath != "" {
		writeLine("# Pinned by absolute path: the service runs under launchd, whose PATH does")
		writeLine("# not include Homebrew. Without this every transcoded format fails with")
		writeLine("# \"Internal Server Error: invalid argument\".")
		writeLine("FFmpegPath = %s", tomlString(ffmpegPath))
		writeLine("")
	}
	writeLine("LogLevel = %s", tomlString("info"))
	writeLine("EnableLogRedacting = true")
	writeLine("")
	writeLine("[Scanner]")
	writeLine("Schedule = %s", tomlString(cfg.Scan.Schedule))
	writeLine("")
	writeLine("[Subsonic]")
	writeLine("# UDL matches Navidrome tracks to Apple Music and Rekordbox by real path.")
	writeLine("DefaultReportRealPath = true")
	writeLine("")
	writeLine("[Backup]")
	writeLine("Path = %s", tomlString(resolved.BackupDir))
	writeLine("Schedule = %s", tomlString(cfg.Backup.Schedule))
	writeLine("Count = %d", cfg.Backup.Count)
	return b.String()
}

// ServicePath is the PATH the launchd service runs with. launchd does not read
// a login shell, so its default PATH has no Homebrew prefix in it and any
// helper Navidrome shells out to — ffmpeg above all — goes missing.
func ServicePath(binaryPath, ffmpegPath string) string {
	seen := map[string]struct{}{}
	var dirs []string
	add := func(dir string) {
		if dir == "" || dir == "." {
			return
		}
		if _, exists := seen[dir]; exists {
			return
		}
		seen[dir] = struct{}{}
		dirs = append(dirs, dir)
	}
	add(filepath.Dir(ffmpegPath))
	add(filepath.Dir(binaryPath))
	for _, dir := range []string{"/opt/homebrew/bin", "/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin"} {
		add(dir)
	}
	return strings.Join(dirs, ":")
}

// RenderLaunchAgent produces the UDL-owned launchd plist.
func RenderLaunchAgent(binaryPath, ffmpegPath string, resolved Resolved) string {
	var b strings.Builder
	writeLine := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}
	writeLine(`<?xml version="1.0" encoding="UTF-8"?>`)
	writeLine(`<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`)
	writeLine(`<!-- %s -->`, OwnershipMarker)
	writeLine(`<plist version="1.0">`)
	writeLine(`<dict>`)
	writeLine(`	<key>Label</key>`)
	writeLine(`	<string>%s</string>`, xmlEscape(LaunchAgentLabel))
	writeLine(`	<key>ProgramArguments</key>`)
	writeLine(`	<array>`)
	writeLine(`		<string>%s</string>`, xmlEscape(binaryPath))
	writeLine(`		<string>--configfile</string>`)
	writeLine(`		<string>%s</string>`, xmlEscape(resolved.ConfigFile))
	writeLine(`	</array>`)
	writeLine(`	<key>EnvironmentVariables</key>`)
	writeLine(`	<dict>`)
	writeLine(`		<key>PATH</key>`)
	writeLine(`		<string>%s</string>`, xmlEscape(ServicePath(binaryPath, ffmpegPath)))
	writeLine(`	</dict>`)
	writeLine(`	<key>RunAtLoad</key>`)
	writeLine(`	<true/>`)
	writeLine(`	<key>KeepAlive</key>`)
	writeLine(`	<true/>`)
	writeLine(`	<key>WorkingDirectory</key>`)
	writeLine(`	<string>%s</string>`, xmlEscape(resolved.DataDir))
	writeLine(`	<key>StandardOutPath</key>`)
	writeLine(`	<string>%s</string>`, xmlEscape(resolved.LogFile))
	writeLine(`	<key>StandardErrorPath</key>`)
	writeLine(`	<string>%s</string>`, xmlEscape(resolved.LogFile))
	writeLine(`	<key>ProcessType</key>`)
	writeLine(`	<string>Background</string>`)
	writeLine(`</dict>`)
	writeLine(`</plist>`)
	return b.String()
}

// IsUDLOwned reports whether managed content carries the ownership marker.
func IsUDLOwned(content string) bool {
	return strings.Contains(content, OwnershipMarker)
}

func tomlString(value string) string {
	return strconv.Quote(value)
}

var xmlEscaper = strings.NewReplacer(
	"&", "&amp;",
	"<", "&lt;",
	">", "&gt;",
	`"`, "&quot;",
	"'", "&apos;",
)

func xmlEscape(value string) string {
	return xmlEscaper.Replace(value)
}
